In [ ]:
# 2유형 = 모델링 및 평가
# 회귀분석 (y 값 = 종속변수가 연속형 변수) = regression
# 분류분석 (y 값 = 종속변수가 이산형 변수) = classification

# 전처리는 결측치, 이상치 등을 처리해줘야함
# 데이터 split = train dataset (80%), test dataset (20%) : 성능평가의 용도로만 쓰이는 데이터(test data)
# train data는 train 60(모델 학습), validation 20(검증, 1차 성능평가), test 20(실제 test data를 모델에 넣어서, 모델이 예측한 값과(예측 y값) 실제 y값 비교 = test data의 실제 y값과 모델이 예측해준 예측 y값 비교

# 테스트 데이터에는 독립변수만 넣는것 !! 종속변수 넣는 게 아님 = 이 test data를 실제 y값과 비교

In [ ]:
# 지금까지 지도학습만 나왔음
# macro F1 score
# RMSE
# Accuracy
# AUC

# 해당 함수를 치면 성능을 구해줌

In [ ]:
# 2유형의 목표 : 적절한 예측값(y)를 제출하는 것 : 성능평가는 출제기관에서 진행
# 적절한 예측값을 제출하기 위해서는 train / validation set으로 나누고, validation set을 가지고 성능 평가를 해봐야한다.

# 실기 시험에서 주어지는 데이터 set
## 1. X_test = pd.read_csv("data/X_test.csv")
## 2. X_train = pd.read_csv("data/X_train.csv")
## 3. y_train = pd.read_csv("daya/Y_train/csv")

### Y_test는 존재안함.

In [ ]:
# 시험에서 제공되는 데이터 : Train data (X, Y) / Test data (X)

# Train data (X, Y) 로 모델이 학습되면 train된 model에 validation x 데이터를 넣음
# validation x만 train model에 넣음!! 여기서 나온 예측값과 실제 값을 비교해야하는데, 실제 값은 validation y값 : 성능이 제대로 나오는지 확인해야함
# 학습된 모델에 (최종) x-test 값을 넣어서 예측 y값을 시험에서 원하는 형태로 제공해야 함

In [ ]:
# 분류(Classification)분석 시 주의사항
# Y(종속변수) 분리할 대 train_test_split 함수에서 "stratify 옵션"을 꼭 해줘야 함(층화 샘플링) = 강의 15분 28초 이미지 참조
# 종속변수의 class가 불균형할 경우 startify 옵션을 안줄경우, 랜덤으로 배정되기 때문에 class 소수 값이 train_set에 들어오지 않을 수도 있기 때문에 아예 소수값을 train 못할수도 있음  : class 값이 동일한 비율로 있지 않기 때문에 validation_ set으로 검즐할 때 꼭 stratify 옵션 줘야함

In [ ]:
# 모델이 학습되면(trained data) : test data set을 넣어 성능 평가를 해야하는데 (test data의 x를 trained model에 넣으면 예측값을 내뱉어줌(y값 예측))
# 성능평가는 실제 y값(test에 있는 y값), 예측 y값 비교하는 것 = 성능지표들로


# 분석 평가 모형 - 회귀 성능 지표 : 실제값과 예측값의 차이를 계산함 모든 지표들이!!
# 실제 값(y)과 예측값(y`) 값의 차이를 계산하여 성능을 측정
## 1. MSE(Mean Squared Error) : 평균 제곱 오차
## 2. RMSE(Root MSE) : 평균 제곱근 오차
## 3. MAE(Mean Absolute Error): 평균 절대 오차
## 4. MAPE(Mean Absolute Percentage Error) : 평균 절대 백분율 오차
## 5. R2(결정계수) : 회귀 모형의 설명력 (0-1 사이의 값을 가지며 값이 클수록 성능이 좋음)

In [ ]:
# 분석모형 평가 - 분류 성능 지표
## 혼동행렬 : 이진분류(0, 1)에서 나올 수 있는 경우의 수 4가지 = 2가지 범주의 y값 !!
## 20분 9초 이미지 참조 : 정확도, 민감도(재현율), 특이도, F1 Score

## Tips
## 1. 예측 / 실제, Postive / Nagative 위치 확인
## 2. 예측 기준으로 4가지 (TP, TN, FP, FN) 항목 위치 표기
##### TP : True Positive (예측 Positive, 실제 Positive)
##### FP : False Positive (예측 Positive, 실제 Nagative)
##### TN : True Nagative (예측 Nagative, 실제 Nagative)
##### FN : False Nagative (예측 Nagative, 실제 Positive)
## 3. 각각의 지표 정의 그대로 계산하기

## 여러가지 지표들 정의를 암기할 것 !
### 1. 정확도(Accuracy): 전체 중에 잘 분류한 비율 (TP + TN / 전체)
### 2. 민감도(Sensitivity): 실제 Positive 중에 잘 분류한 비율 = 재현율(Recall) (TP / TP + FN) : * FN : 예측을 N으로 했는데 실제 P이다
### 3. 특이도(Specificity): 실제 Nagative 중에 잘 분류한 비욜 (TN / TN + FP)
### 4. 정밀도(Precision): 예측 Positive 중에 잘 분류한 비율 (TP / TP + FP)
### 5. F1 Score = (2 * 정밀도 * 재현율) / (정밀도 + 재현율)

In [ ]:
# 분석 모형 평가 - 분류 성능 지표
## ROC Curve
## AUC (Area Under the Curve): ROC Curve의 아래쪽 면적을 뜻함, 0.5~1.0 값을 가지며 1로 갈수록 분류 성능이 좋음
### 0.9 ~ 1.0 뛰어남 (Excellent)
### 0.8 ~ 0.9 우수함 (Good)
### 0.7 ~ 0.8 보통 (Fair)
### 0.6 ~ 0.7 불량 (Poor)
### 0.5 ~ 0.6 실패 (Fail)

## ROC Curve의 y축은 재현율(TPR) , x축은 (1-특이도) = FPR

In [ ]:
# 데이터 전처리
## 1. 데이터 탐색
## 2. 결측값 / 이상값 처리
## 3. 변수 처리

# 전처리 데이터를 가지고 모델링 및 성능 평가

In [ ]:
# 데이터 전처리
## 데이터 탐색 (EDA)
### 1. 행/열 확인: df.shape
### 2. 초기 데이터 확인: df.head()
### 3. 데이터 정보 확인: df.info() - 변수명, 데이터 수, 결측치 수, 데이터 타입 등
### 4. 기초 통계량 확인: df.describe() - 연속형 변수
### 5. 범주형 변수 빈도: df.value_counts() - 범주형 변수

## 결측값 확인 및 처리
### 1. 결측치 확인: df.isnull().sum()
### 2. 결측치 삭제(행 기준): df.dropna() - 실기 시험에서 전체 데이터 수에 비해 결측값이나 이상값 비율이 작다면 삭제, 정보 손실이 발생하기 때문에 감안해야 함 (조금 더 모델의 성능을 올리고 싶다면, 결측치 삭제가 아니라 결측치를 대체해줘야 함)
### 3. 결측치 대체: df['A'].median(), df['A'].mean(), df['A'].mode() - 연속형 데이터(중앙값이나 평균값으로 대체, 중앙값이 이상치에 민감하지 않기 때문에 보완되므로 중앙값으로 하는 걸 추천함) / 범주형 데이터(최빈값으로 대체)

## 이상값 확인 및 처리
### 1. 이상값 확인: df.describe() - train / test 데이터 분포 형태를 확인해서 이상치 여부 확인, 논리적으로 설명할 수 없는 데이터 (보통 min / max 값에서 확인) (ex. 중고차 생산년도 2060년, 나이 -20, 성별 T 등)
### 2. 이상값 처리 (train / test data set 분포를 둘 다 살펴보기 - 두 데이터에 섞여 있으면, train data에서 이상값을 학습하는 게 더 낫다.)
# - 대체 (연속형 데이터 - 극단값은 최소값이거나, 최대값으로 대체)
# - 대체 (범주형 데이터는 최빈값으로 대체)

# ** 해당 데이터를 처리해줬을 때의 성능과 처리하지 않았을 경우의 성능을 비교해서 더 나은 성능을 가진 것을 사용하기 (차이가 있으면 좋은쪽으로 선택하고, 차이가 없으면 그대로 둬도 됨)

## 분석 변수 처리
### 1. 불필요한 변수 삭제
#### df = df.drop(columns = ['변수1', '변수2'])
#### df = df.drop(['변수1', '변수2'], axis=1) - 열 기준 삭제
### 2. 필요시 파생변수 생성 - 권하지는 않음 !! (개인의 선택일 뿐)
### 3. 원핫인코딩 (문자형 데이터 처리하기) - 머신러닝 모델이 문자형 데이터 처리 못하니까 원핫인코딩 해줘야
#### x_train = pd.get_dummies(x_train)
#### x_test = pd.get_dummies(x_test)

In [ ]:
# 모델 선정 - RandomForest
# 랜덤 포레스트를 사용하는 이유
## 1. 분류/회귀 문제에 모두 사용 가능
## 2. 모형 자체가 앙상블 모형이라 성능이 좋음
## 3. 이상치에 민감하지 않고, 분석 속도도 적절함

# 다수의 의사결정 나무를 만든다음에, 새로운 데이터가 들어왔을 때 각각의 의사결정 나무에 넣어서 나온 결과들을 투표를 해서 최종 결과값을 내는 것! (다수결의 원칙)
# 이진분류라면 모델이 3개 있다고 할 때 A / B / B로 분류했다고 할 때 최종 클래스는 B가 되는 것.

In [ ]:
# 2유형 summary
# 2유형 분석 순서
## 1. 라이브러리 및 데이터 확인
## 2. 데이터 탐색(EDA) - 데이터 타입, 결측치, 기초 통계량 등
## 3. 데이터 전처리 및 분리
### 결측치/이상치 : 대체 or 삭제
### 변수처리: 변수 선택/추가, 원핫인코딩
## 4. 모델링 및 성능 평가
### 분류 - randomForestClassifier - Accuracy, F1 Score
### 회귀 - randomForestRegressor - R2, MSE, RMSE
## 5. 예측값 제출

In [ ]:
## 가능하면 30초 이내에 분석이 끝나야 함!! 기준은 1분이긴 함.

In [ ]:
# 제 2유형 - 연습하기 - 와인 종류 분석 (회귀, 분류 둘 다 똑같음)
# 데이터 분석 순서
# 1. 라이브러리 및 데이터 확인
# 2. 데이터 탐색 (EDA)
# 3. 데이터 전처리 및 분리
# 4. 모델링 및 성능평가
# 5. 예측값 제출

# 1. 라이브러리 및 데이터 확인

In [18]:
## 기초 라이브러리 - pandas, numpy
import pandas as pd
import numpy as np

In [19]:
########## 실기환경 복사 영역 ##################
###### 실기 환경에서 sklearn library 사용 가능하기 때문에 이거 잘 활용하기 ######
from sklearn.datasets import load_wine
# 와인 datasets load
wine = load_wine()
x = pd.DataFrame(wine.data, columns=wine.feature_names)
y = pd.DataFrame(wine.target)

# 실기 시험 데이터셋으로 셋팅하기 (수정 금지)
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, stratify=y, random_state=2023)

x_test = pd.DataFrame(x_test)
x_train = pd.DataFrame(x_train)
y_train = pd.DataFrame(y_train)

x_test.reset_index()
y_train.columns = ['target']
########## 실기환경 복사 영역 ##################

In [ ]:
## 참고사항 ##
# y_test는 실기 문제상에 주어지지 않음
# TIP: X를 대문자로 쓰지 말고, 소문자  x로 쓰세요. 시험에서 실수하기 쉽습니다.
# 보통 X는 2차원 배열이라 대문자로쓰고, y는 1차원 배열이라 소문자인데, 아래 X라고 대문자로 세팅되어있지만, 소문자 x로 바꾸기!!
# 실기시험 데이터 형식 (실제 시험장에서는 다르 수 있으니 반드시 체크)
# X_test = pd.read_csv('data/X_test.csv')
# X_train = pd.read_csv('data/X_train.csv')
# y_train = pd.read_csv('data/y_train.csv')

## ** 문제 풀기 전에 소문자 x로 바꾸고, x data set !!
## ** 그리고 실제 시험 data set의 train set이 나눠져있지 않고 붙어 있을수도 있다 !!

In [ ]:
# 실제 시험에서 문제 정확히 읽는 게 중요함 !!

# 와인의 종류를 분류해보자
# - 데이터의 결측치, 이상치에 대해 처리하고, 분류 모델을 사용하여 정확도 / f1 score / auc 값을 산출하시오.
# - 제출은 result 변수에 담아 양식에 맞게 제출하시오.

In [20]:
# 데이터 설명
print(wine.DESCR)

.. _wine_dataset:

Wine recognition dataset
------------------------

**Data Set Characteristics:**

    :Number of Instances: 178
    :Number of Attributes: 13 numeric, predictive attributes and the class
    :Attribute Information:
 		- Alcohol
 		- Malic acid
 		- Ash
		- Alcalinity of ash  
 		- Magnesium
		- Total phenols
 		- Flavanoids
 		- Nonflavanoid phenols
 		- Proanthocyanins
		- Color intensity
 		- Hue
 		- OD280/OD315 of diluted wines
 		- Proline

    - class:
            - class_0
            - class_1
            - class_2
		
    :Summary Statistics:
    
    ============================= ==== ===== ======= =====
                                   Min   Max   Mean     SD
    ============================= ==== ===== ======= =====
    Alcohol:                      11.0  14.8    13.0   0.8
    Malic Acid:                   0.74  5.80    2.34  1.12
    Ash:                          1.36  3.23    2.36  0.27
    Alcalinity of Ash:            10.6  30.0    19.5   3.3
    Ma

# 2. 데이터 탐색

In [21]:
## 데이터의 행/열 확인 - shape
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)

(142, 13)
(36, 13)
(142, 1)


In [22]:
## 초기 데이터 확인
print(x_train.head(3))
print(x_test.head(3))
print(y_train.head(3))

     alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
52     13.82        1.75  2.42               14.0      111.0           3.88   
146    13.88        5.04  2.23               20.0       80.0           0.98   
44     13.05        1.77  2.10               17.0      107.0           3.00   

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
52         3.74                  0.32             1.87             7.05  1.01   
146        0.34                  0.40             0.68             4.90  0.58   
44         3.00                  0.28             2.03             5.04  0.88   

     od280/od315_of_diluted_wines  proline  
52                           3.26   1190.0  
146                          1.33    415.0  
44                           3.35    885.0  
     alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
168    13.58        2.58  2.69               24.5      105.0           1.55   
144    12.25        

In [23]:
# 변수명과 데이터 타입이 매칭이 되는지, 결측치가 있는지 확인
## info() 함수로 볼 수 있는건 142개의 데이터가 있고 13개의 열이 있다는 것
print(x_train.info())
print(x_test.info())
print(y_train.info())

# ** 만약 info 했을 때 float, int 아니라 object 있다면 원핫인코딩 해줘야 함

<class 'pandas.core.frame.DataFrame'>
Index: 142 entries, 52 to 115
Data columns (total 13 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   alcohol                       142 non-null    float64
 1   malic_acid                    142 non-null    float64
 2   ash                           142 non-null    float64
 3   alcalinity_of_ash             142 non-null    float64
 4   magnesium                     142 non-null    float64
 5   total_phenols                 142 non-null    float64
 6   flavanoids                    142 non-null    float64
 7   nonflavanoid_phenols          142 non-null    float64
 8   proanthocyanins               142 non-null    float64
 9   color_intensity               142 non-null    float64
 10  hue                           142 non-null    float64
 11  od280/od315_of_diluted_wines  142 non-null    float64
 12  proline                       142 non-null    float64
dtypes: float6

In [24]:
# x_train과 x_test 데이터의 기초 통계량을 잘 비교해보기
## 잘 비교해보라는 게 어떤 의미냐면, train data와 test data의 분포가 비슷해야한다. 예를 들면 알코올에 대한 train data의 평균값은 13, test data의 평균값은 12.9 이렇게 train data와 test data의 분포가 비슷해야 한다!!
## 이상치가 있으며 train data와 test data의 min / max 값의 차이가 많이 난다 !! - 이거 주의

## describe에서는 분포 확인
print(x_train.describe())  # x_train.describe().T 편한 거 사용하기
print(x_test.describe())
print(y_train.describe())

          alcohol  malic_acid         ash  alcalinity_of_ash   magnesium  \
count  142.000000  142.000000  142.000000         142.000000  142.000000   
mean    13.025915    2.354296    2.340211          19.354225   98.732394   
std      0.812423    1.142722    0.279910           3.476825   13.581859   
min     11.030000    0.740000    1.360000          10.600000   70.000000   
25%     12.370000    1.610000    2.190000          16.800000   88.000000   
50%     13.050000    1.820000    2.320000          19.300000   97.000000   
75%     13.685000    3.115000    2.510000          21.500000  106.750000   
max     14.830000    5.800000    3.230000          30.000000  151.000000   

       total_phenols  flavanoids  nonflavanoid_phenols  proanthocyanins  \
count     142.000000  142.000000            142.000000       142.000000   
mean        2.303592    2.043592              0.361479         1.575070   
std         0.633955    1.033597              0.124627         0.576798   
min         0.9

In [12]:
print(x_train.describe().T)  ## 행 / 열 전환

                              count        mean         std     min       25%  \
alcohol                       142.0   13.025915    0.812423   11.03   12.3700   
malic_acid                    142.0    2.354296    1.142722    0.74    1.6100   
ash                           142.0    2.340211    0.279910    1.36    2.1900   
alcalinity_of_ash             142.0   19.354225    3.476825   10.60   16.8000   
magnesium                     142.0   98.732394   13.581859   70.00   88.0000   
total_phenols                 142.0    2.303592    0.633955    0.98    1.7575   
flavanoids                    142.0    2.043592    1.033597    0.34    1.2275   
nonflavanoid_phenols          142.0    0.361479    0.124627    0.14    0.2700   
proanthocyanins               142.0    1.575070    0.576798    0.41    1.2425   
color_intensity               142.0    5.005070    2.150186    1.28    3.3000   
hue                           142.0    0.950394    0.220736    0.54    0.7825   
od280/od315_of_diluted_wines

In [25]:
# y 데이터도 구체적으로 살펴보기
print(y_train.head())
print(y_train.value_counts())

     target
52        0
146       2
44        0
67        1
43        0
target
1         57
0         47
2         38
Name: count, dtype: int64


In [26]:
# 3. 데이터 전처리 및 분리
## 1) 결측치
print(x_train.isnull().sum())
print(x_test.isnull().sum())
print(y_train.isnull().sum())

alcohol                         0
malic_acid                      0
ash                             0
alcalinity_of_ash               0
magnesium                       0
total_phenols                   0
flavanoids                      0
nonflavanoid_phenols            0
proanthocyanins                 0
color_intensity                 0
hue                             0
od280/od315_of_diluted_wines    0
proline                         0
dtype: int64
alcohol                         0
malic_acid                      0
ash                             0
alcalinity_of_ash               0
magnesium                       0
total_phenols                   0
flavanoids                      0
nonflavanoid_phenols            0
proanthocyanins                 0
color_intensity                 0
hue                             0
od280/od315_of_diluted_wines    0
proline                         0
dtype: int64
target    0
dtype: int64


In [ ]:
## 결측치 제거
## df = df.dropna()  # 행 기준 결측치 제거 !!
## print(df)

# 참고사항
# print(df.dropna().shape)  # shape 찍어보면 행 기준으로 얼마나 삭제됐는지 알 수 있음

In [ ]:
## 결측치 대체 (평균값, 중앙값, 최빈값)
# - 연속형 변수 : 중앙값, 평균값 : 중앙값을 더 추천함 (이상치, 극단값의 영향을 덜 받기 때문에)
## df['변수명'].median()
## df['변수명'].mean()
# - 범주형 변수 : 최빈값  df['변수명'].mode()

## 결측치 대체
# df['변수명'] = df['변수명'].fillna(대체할 값)

In [ ]:
## 2) 이상치 대체 (예시)
# df['변수명'] = np.where(df['변수명'] >=5, 대체할 값, df['변수명'])

In [ ]:
## 3) 변수 처리하기 - 불필요한 변수 제거, 필요한 변수만 사용하기 -> 원핫인코딩(변수가 숫자 형태로 되어있어야 하는데, 문자형으로 되어있으면 빅데이터 분석이 되지 않기 때문에 원핫인코딩 해줘야함)

# 불필요한 변수 제거
# df = df.drop(columns = ['변수1', '변수2'])
# df = df.drop(['변수1', '변수2'], axis = 1) #  열 기준 삭제

# 필요시 변수 추가 (파생변수 생성)
# df['파생변수명'] = df['A'] * df['B']  # 파생변수 생성 수식

# 원핫인코딩 (가변수 처리)
# x_train = pd.get_dummies(x_train)
# x_test = pd.get_dummies(x_test)
# print(x_train.info())
# print(x_test.info())

# 3. 데이터 분리

In [27]:
# 데이터를 훈련 세트와 검증용 세트로 분할(80% 훈련, 20% 검증용) - train data를 train / validation으로 나눠야함
from sklearn.model_selection import train_test_split
x_train, x_val, y_train, y_val = train_test_split(
    x_train,  # x와 y가 이미 들어와야하고,
    y_train['target'],
    test_size=0.2,  # test size는 어떻게 할건지
    stratify=y_train['target'],  # y값에 대해 반드시 stratify 지정해줘야 함
    random_state=2023)  # random state를 지정하면 랜덤이지만 고정이됨

print(x_train.shape)
print(x_val.shape)
print(y_train.shape)
print(y_val.shape)

(113, 13)
(29, 13)
(113,)
(29,)


# 4. 모델링 및 성능 평가

In [28]:
# 랜덤포레스트 모델 사용 (참고: 회귀 모델은 RandomForestRegressor
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier()
model.fit(x_train, y_train)  # 학습 - train data를 넣어야 함 (x_train, y_train)

RandomForestClassifier()

In [29]:
# 모델을 사용하여 테스트 데이터 예측
y_pred = model.predict(x_val)

In [30]:
# 모델 성능 평가 (정확도, F1 Score, 민감도, 특이도 등)
from sklearn.metrics import accuracy_score, f1_score, recall_score,precision_score, roc_auc_score

acc = accuracy_score(y_val, y_pred)  # 실제값, 예측값
f1 = f1_score(y_val, y_pred, average = 'macro')  # 실제값, 예측값
# auc = roc_auc_score(y_val, y_pred)  # 실제값, 예측값, * AUC는 이진분류만 구할 수 있음 - 다중분류에서는 불가능 !! (지금은 와인 종류 3가지로 분류하고 있기 때문에 삼중분류임)

In [31]:
print(acc)

0.9655172413793104


In [32]:
print(f1)  # macro f1 score

0.9670588235294119


# 5. 예측값 제출
- 주의 !! test set을 모델에 넣어 나온 예측값을 제출해야 함 !!

In [34]:
# (실기시험 안내사항)
# 아래 코드 예측 변수와 수험번호를 개인별로 변경하여 활용
# pd.DataFrame({'result': y_result}).to_csv('수험번호.csv', index= False)

# 모델을 사용하여 테스트 데이터 예측

# 1. 특정 클래스로 분류할 경우 (predict)
y_result = model.predict(x_test)
print(y_result[:5])

# 2. 특정 클래스로 분류될 확률을 구할 경우 (predict_proba)
y_result_prob = model.predict_proba(x_test)
print(y_result_prob[:5])

# 이해해보기
result_prob = pd.DataFrame({
    'result': y_result,
    'prob_0': y_result_prob[:, 0],  # 모든 행, 0번째 열
    'prob_1': y_result_prob[:, 1],  # 모든 행, 1번째 열
    'prob_2': y_result_prob[:, 2]   # 모든 행, 2반쩨 얄
})
# class가 0일 확률: y_result_prob[:,0]
# class가 1일 확률: y_result_prob[:,1]
# class가 2일 확률: y_result_prob[:,2]

print(result_prob[:5])

[2 2 2 0 1]
[[0.01 0.05 0.94]
 [0.06 0.13 0.81]
 [0.01 0.06 0.93]
 [0.97 0.03 0.  ]
 [0.05 0.86 0.09]]
   result  prob_0  prob_1  prob_2
0       2    0.01    0.05    0.94
1       2    0.06    0.13    0.81
2       2    0.01    0.06    0.93
3       0    0.97    0.03    0.00
4       1    0.05    0.86    0.09


In [ ]:
# ** tip: 데이터를 저장한 다음 불러와서 제대로 제출했는지 확인하기
